2019-11-09 11:32:32.766714: W external/org_tensorflow/tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'libcuda.so.1'; dlerror: libcuda.so.1: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /pkgs/cuda-10.0/lib64:/pkgs/cudnn-10.0-v7.4.2/lib64:
2019-11-09 11:32:32.766750: E external/org_tensorflow/tensorflow/stream_executor/cuda/cuda_driver.cc:334] failed call to cuInit: UNKNOWN ERROR (303)
/scratch/hdd001/home/jkelly/jax_nodes/jax/lib/xla_bridge.py:115: UserWarning: No GPU/TPU found, falling back to CPU.
  warnings.warn('No GPU/TPU found, falling back to CPU.')
Reg: none	Lambda 0.0000e+00
Iter 0010 | Total (Regularized) Loss 0.139010 | Loss 0.139010 | r0 0.849257 | r1 0.206079
Iter 0020 | Total (Regularized) Loss 0.136693 | Loss 0.136693 | r0 0.870928 | r1 0.251969
Iter 0030 | Total (Regularized) Loss 0.135858 | Loss 0.135858 | r0 0.872053 | r1 0.254144
Iter 0040 | Total (Regularized) Loss 0.135037 | Loss 0.135037 | r0 0.872656 | r1 0.255213
Iter 0050 | Total (Regularized) Loss 0.134525 | Loss 0.134525 | r0 0.873197 | r1 0.257215
Iter 0060 | Total (Regularized) Loss 0.133438 | Loss 0.133438 | r0 0.873745 | r1 0.257255
Iter 0070 | Total (Regularized) Loss 0.132628 | Loss 0.132628 | r0 0.874234 | r1 0.258115
Iter 0080 | Total (Regularized) Loss 0.131803 | Loss 0.131803 | r0 0.874700 | r1 0.259014
Iter 0090 | Total (Regularized) Loss 0.130952 | Loss 0.130952 | r0 0.875155 | r1 0.259938
Iter 0100 | Total (Regularized) Loss 0.130138 | Loss 0.130138 | r0 0.875576 | r1 0.261226
